services:
  # Redis service for local development
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    # Only start if REDIS_HOST is set to 'redis' (local development)
    profiles:
      - local

  api:
    build: ./api
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - BASE_URL=${BASE_URL:-}
      - LOGGING=${LOGGING:-true}
      - ENABLE_PACKAGE_DIFFING=${ENABLE_PACKAGE_DIFFING:-true}
      - ENABLE_ACCOUNT_REGISTRATION=${ENABLE_ACCOUNT_REGISTRATION:-true}
      - DEBUG_DISABLE_AUTH=${DEBUG_DISABLE_AUTH:-false}
      - DEBUG_USER_ID=${DEBUG_USER_ID:-}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}
      - REDIS_TLS_DISABLED=${REDIS_TLS_DISABLED:-}
      - CODE_PUSH_SERVER_URL=${CODE_PUSH_SERVER_URL:-}
    restart: unless-stopped
