name: Simple Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  CODEPUSH_GITHUB_CLIENT_ID_PROD: ${{ secrets.CODEPUSH_GITHUB_CLIENT_ID_PROD }}
  CODEPUSH_GITHUB_CLIENT_SECRET_PROD: ${{ secrets.CODEPUSH_GITHUB_CLIENT_SECRET_PROD }}
  REDIS_HOST_PROD: cache.9eczd4.0001.use1.cache.amazonaws.com
  REDIS_PORT_PROD: 6379
  REDIS_DB_PROD: 1

jobs:
  deploy-prod:
    runs-on: prod

    steps:
    - name: Get CodePush instance details
      id: get-instance
      run: |
        # Get instance private IP from CloudFormation
        PRIVATE_IP=$(aws cloudformation describe-stacks \
          --stack-name CodePushServerProdStack \
          --region ${{ env.AWS_REGION }} \
          --query 'Stacks[0].Outputs[?OutputKey==`CodePushPrivateIP`].OutputValue' \
          --output text)
        
        # Get infrastructure values for environment config
        BUCKET_NAME=$(aws cloudformation describe-stacks \
          --stack-name CodePushServerProdStack \
          --region ${{ env.AWS_REGION }} \
          --query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' \
          --output text)
        
        SERVER_URL=$(aws cloudformation describe-stacks \
          --stack-name CodePushServerProdStack \
          --region ${{ env.AWS_REGION }} \
          --query 'Stacks[0].Outputs[?OutputKey==`CodePushServerURL`].OutputValue' \
          --output text)
        
        echo "private-ip=$PRIVATE_IP" >> $GITHUB_OUTPUT
        echo "bucket-name=$BUCKET_NAME" >> $GITHUB_OUTPUT
        echo "server-url=$SERVER_URL" >> $GITHUB_OUTPUT

    - name: Get SSH key for deployment
      run: |
        # Get SSH key from Parameter Store
        KEY_PAIR_NAME=$(aws cloudformation describe-stacks \
          --stack-name CodePushServerProdStack \
          --region ${{ env.AWS_REGION }} \
          --query 'Stacks[0].Outputs[?OutputKey==`KeyPairName`].OutputValue' \
          --output text)
        
        KEY_PAIR_ID=$(aws ec2 describe-key-pairs \
          --key-names $KEY_PAIR_NAME \
          --region ${{ env.AWS_REGION }} \
          --query 'KeyPairs[0].KeyPairId' \
          --output text)
        
        aws ssm get-parameter \
          --name "/ec2/keypair/$KEY_PAIR_ID" \
          --region ${{ env.AWS_REGION }} \
          --with-decryption \
          --query 'Parameter.Value' \
          --output text > codepush_key.pem
        
        chmod 400 codepush_key.pem

    - name: Deploy to Production CodePush Server
      run: |
        echo "🚀 Deploying to CodePush PRODUCTION server..."
        echo "Target: ${{ steps.get-instance.outputs.private-ip }}"
        
        ssh -i codepush_key.pem \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          ubuntu@${{ steps.get-instance.outputs.private-ip }} << EOF
        
        set -e
        echo "📍 Starting PRODUCTION deployment on CodePush server..."
        
        cd /opt/codepush
        
        # Clone repo on first deployment, pull on subsequent deployments
        if [ ! -d ".git" ]; then
          echo "🔄 First deployment - cloning repository..."
          git clone https://github.com/crabi/code-push-server.git .
        else
          echo "🔄 Pulling latest changes..."
          git pull origin main
        fi
        
        # Create production environment configuration with values from infrastructure
        echo "⚙️ Creating PRODUCTION environment configuration..."
        {
          echo "# CodePush Server - PRODUCTION Environment"
          echo "NODE_ENV=production"
          echo "BASE_URL="
          echo "LOGGING=false"
          echo "ENABLE_PACKAGE_DIFFING=true"
          echo "ENABLE_ACCOUNT_REGISTRATION=false"
          echo ""
          echo "# AWS S3 Configuration (using IAM role)"
          echo "AWS_BUCKET_NAME=${{ steps.get-instance.outputs.bucket-name }}"
          echo "AWS_REGION=${{ env.AWS_REGION }}"
          echo ""
          echo "# Authentication Settings (production - no debug mode)"
          echo "DEBUG_DISABLE_AUTH=false"
          echo "DEBUG_USER_ID="
          echo ""
          echo "# Redis Configuration"
          echo "REDIS_HOST=${{ env.REDIS_HOST_PROD }}"
          echo "REDIS_PORT=${{ env.REDIS_PORT_PROD }}"
          echo "REDIS_DB=${{ env.REDIS_DB_PROD }}"
          echo "REDIS_TLS_DISABLED=true"
          echo ""
          echo "# GitHub OAuth (injected from GitHub secrets)"
          echo "GITHUB_CLIENT_ID=${{ env.CODEPUSH_GITHUB_CLIENT_ID_PROD }}"
          echo "GITHUB_CLIENT_SECRET=${{ env.CODEPUSH_GITHUB_CLIENT_SECRET_PROD }}"
          echo ""
          echo "# Server Configuration"
          echo "CODE_PUSH_SERVER_URL=${{ steps.get-instance.outputs.server-url }}"
          echo "PORT=3000"
        } > .env.prod
        
        echo "🐳 Restarting PRODUCTION containers..."
        docker-compose --env-file .env.prod down || true
        docker-compose --env-file .env.prod up --build -d
        
        echo "⏳ Waiting for containers to start..."
        sleep 20
        
        echo "📊 Production deployment status:"
        docker-compose --env-file .env.prod ps
        
        echo "✅ PRODUCTION deployment completed successfully!"
        EOF

    - name: Verify production deployment
      run: |
        echo "🔍 Verifying PRODUCTION deployment..."
        echo "🌐 Production URL: ${{ steps.get-instance.outputs.server-url }}"
        
        # Health check with longer wait for production
        sleep 10
        if curl -f -s "${{ steps.get-instance.outputs.server-url }}" > /dev/null; then
          echo "✅ Production CodePush server is responding!"
        else
          echo "⚠️ Production server might still be starting up"
        fi

    - name: Cleanup
      if: always()
      run: rm -f codepush_key.pem
